export default dogesay = [
	`wow`,
	`tinfoil hat`,
	`what are you doing`,
	`wow very biscits`,
	`straigt to my thigh`,
	`very Speed`,
	`w-a-p-e`,
	`keep your hands away from me`,
	`Concern`,
	`so scare`,
	`so mystery`,
	`much delishush`,
	`So Sochi`,
	`i looc cool`,
	`BORK`,
	`Dis is de way`,
	`Bitconneeeeeeect`,
	`Skraaa`,
	`I luk kawl`,
	`U gud`,
	`2 da moon`,
	`when Lambo Moon?`,
];
